#pragma once

#include <QtGlobal>

#if defined(QTCREATORSTATICANALYSISPLUGIN_LIBRARY)
#  define QTCREATORSTATICANALYSISPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTCREATORSTATICANALYSISPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif
